### ISSUE TITLE
Documentation wrong about install

### ISSUE THREAD

**Issue by D3strukt0r** [marcofugaro/browserslist-to-esbuild#12]
In following two lines i guess you still have the wrong command documented since in your 2.0.0 release you say that `browserslist ` is now a peer dependency

https://github.com/marcofugaro/browserslist-to-esbuild/blob/f4126fce798ac47576c7074ef27a2b8ab7dcf656/readme.md?plain=1#L12

```shell
npm install --save-dev browserslist browserslist-to-esbuild
```

https://github.com/marcofugaro/browserslist-to-esbuild/blob/f4126fce798ac47576c7074ef27a2b8ab7dcf656/readme.md?plain=1#L18

```shell
yarn add --dev browserslist browserslist-to-esbuild
```

**Comment by marcofugaro** [comment]
I added a note in 59cbe02ff80b46b0852c29209336f6a14245496f but I guess is not enough
