### ISSUE TITLE
[Feature Request] Add support for environments

### ISSUE THREAD

**Issue by kuoruan** [marcofugaro/browserslist-to-esbuild#9]
See: https://github.com/browserslist/browserslist?tab=readme-ov-file#configuring-for-different-environments

Config files like:

```
[production]
> 1%
not dead

[modern]
last 1 chrome version
last 1 firefox version

[ssr]
node 12
```

**Comment by marcofugaro** [comment]
It already works, [I added a test for it](https://github.com/marcofugaro/browserslist-to-esbuild/blob/main/test/fixtures/package.json).

Does it not work for you?

**Comment by kuoruan** [comment]
Yes, it works.
But it will be better add some option like babel's `browserslistEnv`
https://babeljs.io/docs/babel-preset-env#browserslistenv

**Comment by kuoruan** [comment]
https://github.com/babel/babel/blob/d7f8401f14779d5615c3ae5d669afcb76dc30432/packages/babel-helper-compilation-targets/src/index.ts#L216-L232

**Comment by marcofugaro** [comment]
Hmm, ok there are now two ways you can specify this option.

Either with [BROWSERSLIST_ENV](https://github.com/browserslist/browserslist?tab=readme-ov-file#configuring-for-different-environments) like this:

```
BROWSERSLIST_ENV=ssr node esbuild.js
```

or with the [options parameter](https://github.com/browserslist/browserslist?tab=readme-ov-file#js-api) like this:

```js
browserslistToEsbuild(undefined, { env: 'ssr' })
```
